[package]
name = "neon"
version = "0.1.0"
authors = ["Sebastian Waisbrot <seppo0010@gmail.com>"]
license = "BSD-3-Clause"
build = "build.rs"
edition = "2018"

[lib]
name = "neon"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.3"

[dependencies]
neon = "0.10"
sha1 = "0.6.0"
